### ISSUE TITLE
Concurrent requests whenever multiple apis are called

### ISSUE THREAD

**Issue by SkiingIsFun123** [SkiingIsFun123/Project-Democracy#20]
Use concurrent requests that waits for both requests to finish before displaying page

**Comment by jevonmao** [comment]
@SkiingIsFun123 Since you moved a lot of the API requests to the backend, is this issue still relevant?

**Comment by SkiingIsFun123** [comment]
@jevonmao Yeah let's get rid of the Google civic api and instead find some api for getting data on ballot measures per state/city. Also local election data for a lot of cities. Let me know if something like that exists.
